<a href="https://colab.research.google.com/github/NDuyHung/DeeplearningTH/blob/main/BaiTHTuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#khởi tạo mang numpy
my_list = np.array([1, 9, 15, 39])
print('List: ', my_list)



List:  [ 1  9 15 39]


In [ ]:
import numpy as np

#Mang 2 chieu
matrix = np.array([
                    #khoi tao dong thu 1 gom 3 phan tu
                    (1, 2, 3),
                    # khoi tao dong thu 2 gom 3 phan tu
                    (4, 5, 6)
                  ])
print(matrix)
#in ra so dong, so cot
print(matrix.shape)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

#mang 3 chieu
a =   np.array([
                [[1., 2., 3.], [4., 5., 6.]],
                [[7., 8., 9.], [10., 11., 12.]]
])
print(a)
print(a.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
import numpy as np

#khởi tạo các ma trận có giá trị 0 và 1
# khởi tạo ma trận 2x2 có giá trị là 0
b = np.zeros((2,2))
# khởi tạo ma trận 2x2 có giá trị là 1
c= np.ones((2, 2))

print('ma trận có giá trị 0')
print(b)
print('ma trận có giá trị 1')
print(c)

ma trận có giá trị 0
[[0. 0.]
 [0. 0.]]
ma trận có giá trị 1
[[1. 1.]
 [1. 1.]]
