<a href="https://colab.research.google.com/github/NDuyHung/DeeplearningTH/blob/main/BaiTHTuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nội dung numpy

In [ ]:
import numpy as np

#khởi tạo mang numpy
my_list = np.array([1, 9, 15, 39])
print('List: ', my_list)



List:  [ 1  9 15 39]


In [ ]:
import numpy as np

#Mang 2 chieu
matrix = np.array([
                    #khoi tao dong thu 1 gom 3 phan tu
                    (1, 2, 3),
                    # khoi tao dong thu 2 gom 3 phan tu
                    (4, 5, 6)
                  ])
print(matrix)
#in ra so dong, so cot
print(matrix.shape)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

#mang 3 chieu
a =   np.array([
                [[1., 2., 3.], [4., 5., 6.]],
                [[7., 8., 9.], [10., 11., 12.]]
])
print(a)
print(a.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
import numpy as np

#khởi tạo các ma trận có giá trị 0 và 1
# khởi tạo ma trận 2x2 có giá trị là 0
b = np.zeros((2,2))
# khởi tạo ma trận 2x2 có giá trị là 1
c= np.ones((2, 2))

print('ma trận có giá trị 0')
print(b)
print('ma trận có giá trị 1')
print(c)

ma trận có giá trị 0
[[0. 0.]
 [0. 0.]]
ma trận có giá trị 1
[[1. 1.]
 [1. 1.]]


In [1]:
import numpy as np

#Thay doi kich thuoc ma tran
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape((3, 2))
print(f)

g= np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)
h = g.reshape((3, 4))
print(h)
j= g.reshape((3, 2, 2))
print(j)
i = g.reshape((2, 3, 2))
print(i)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [2]:
import numpy as np

#chuyen array ve 1 chieu
e= np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
f = e.flatten()
print(f)

g= np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print(j)

[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [3]:
import numpy as np

# them dong du lieu voi hstack va vstack
f= np.array([1., 2., 3.])
g= np.array([4., 5., 6.])
h= np.hstack('hstack \n',(f, g))
print(h)
i= np.vstack('vstack \n',(f, g))
print(i)

[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
import numpy as np

#sinh mang ngau nhien
a= np.random.randint(100, size=(5,  ))
print('Random 1-D array\n', a)
b= np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
c= np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)
#

Random 1-D array
 [39 47 42 43 18]
Random 2-D array
 [[37 77 98 59]
 [32 34 81  3]
 [96 25  8 26]]
Random 3-D array
 [[[52 66 11]
  [75 51 90]
  [98 10 64]
  [23 36 22]]

 [[80  7 65]
  [96  9  3]
  [78  3 65]
  [21 55 38]]

 [[24 48 95]
  [46 96 40]
  [ 9 76 55]
  [57 86 45]]]


In [5]:
import numpy as np

#sinh mang ngau nhien mang so thuc [0, 1]
a= np.random.rand(5)
print('Random 1-D array\n', a)
b= np.random.rand(3, 4)
print('Random 2-D array\n', b)
c= np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.67554873 0.0513364  0.22193423 0.54130414 0.86003631]
Random 2-D array
 [[0.22361524 0.93278798 0.76061557 0.11056241]
 [0.97090019 0.32402326 0.45070676 0.46286594]
 [0.81551352 0.18635267 0.75695952 0.73171566]]
Random 3-D array
 [[[0.35629764 0.36904284 0.87795621]
  [0.7433397  0.69059998 0.43063964]
  [0.30308847 0.9773873  0.06635896]
  [0.22389989 0.2527807  0.25236767]]

 [[0.00608666 0.01523636 0.55822606]
  [0.41460421 0.97454102 0.61430877]
  [0.06309282 0.08812658 0.92626865]
  [0.90363548 0.07281275 0.47875925]]

 [[0.25155469 0.19306431 0.39478123]
  [0.97893147 0.80123083 0.5283485 ]
  [0.24344668 0.91144915 0.12955737]
  [0.66052892 0.70646072 0.17340627]]]


In [7]:
import numpy as np

#sinh mang ngau nhien tu mang gia tri cho truoc
a = np.random.choice([7, 9, 11, 22, 6, 5, 1, 2])
print(a)
#sinh ma tran 3x5 tu mang gia tri cho truoc
b = np.random.choice([7, 9, 11, 22, 6, 5, 1, 2], size=(3, 5))
print(b)


6
[[11 22  7 11  2]
 [ 6 11  1  7  6]
 [ 6  9  9  2  2]]


In [9]:
import numpy as np

#thay doi gia tri cua ma tran
## tao ma tran 5x5 với so 1
a= np.matrix(np.ones((5, 5)))
print(a)
np.array(a)[2]= 5
print('Thay doi gia tri thu 3 cua hang trong mang\n', a)
np.asanyarray(a)[2]=2
print('thay doi gia trị thu 3 hang trong mang với asarray\n', a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay doi gia tri thu 3 cua hang trong mang
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
thay doi gia trị thu 3 hang trong mang với asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
import numpy as np

#Dung ham arange
##sinh day so theo khoang cho truoc
###tao 20 so nguyen tu 1 -> (n-1)
a= np.arange(1, 20)
print(a)
###tao 20 so nguyen tu 1 -> (n-1), moi buoc tang 2 gia tri
b= np.arange(1, 20, 2)
print(b)

#dung ham linspace
c= np.linspace(1., 10. , num = 20)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [12]:
import numpy as np

#index và slice
##slice
a= np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('first row: ', a[0])
print('second row: ', a[1])

#indexing
print('second column', a[:, 1])
print('first column', a[:, 0])
print('first two values of second row: ', a[1, :2])


[[1 2 3]
 [4 5 6]]
first row:  [1 2 3]
second row:  [4 5 6]
second column [2 5]
first column [1 4]
first two values of second row:  [4 5]
